
services:
  etcd:
    image: quay.io/coreos/etcd:v3.5.9
    container_name: etcd-prediction
    command: >
      /usr/local/bin/etcd
      --name etcd0
      --data-dir /etcd-data
      --advertise-client-urls http://0.0.0.0:2378
      --listen-client-urls http://0.0.0.0:2378
      --initial-advertise-peer-urls http://0.0.0.0:2381
      --listen-peer-urls http://0.0.0.0:2381
      --initial-cluster etcd0=http://0.0.0.0:2381
      --initial-cluster-state new
      --initial-cluster-token etcd-token
    ports:
      - "2378:2378"
      - "2381:2381"
    volumes:
      - etcd-data:/etcd-data
    networks:
      - snet-net

  prediction-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: prediction-service
    ports:
      - "50052:50052"
    networks:
      - snet-net

  snet-daemon:
    build: ./snet-daemon/snet-daemon/docker
    image: snet-daemon:v6.1.0
    container_name: snet-daemon-prediction
    depends_on:
      - etcd
      - prediction-service
    ports:
      - "7001:7001"
    volumes:
      - ./snetd.config.json:/etc/singnet/snetd.config.json:ro

    networks:
      - snet-net

volumes:
  etcd-data:

networks:
  snet-net:
    driver: bridge

