# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import service_pb2 as protos_dot_service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class PredictionAnalyticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.UploadCSV = channel.unary_unary(
                '/PredictionAnalytics.PredictionAnalyticsService/UploadCSV',
                request_serializer=protos_dot_service__pb2.UploadCSVRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.UploadCSVResponse.FromString,
                _registered_method=True)
        self.GetSeasonalStats = channel.unary_unary(
                '/PredictionAnalytics.PredictionAnalyticsService/GetSeasonalStats',
                request_serializer=protos_dot_service__pb2.GetSeasonalStatsRequest.SerializeToString,
                response_deserializer=protos_dot_service__pb2.GetSeasonalResponse.FromString,
                _registered_method=True)


class PredictionAnalyticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def UploadCSV(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSeasonalStats(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PredictionAnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'UploadCSV': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadCSV,
                    request_deserializer=protos_dot_service__pb2.UploadCSVRequest.FromString,
                    response_serializer=protos_dot_service__pb2.UploadCSVResponse.SerializeToString,
            ),
            'GetSeasonalStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSeasonalStats,
                    request_deserializer=protos_dot_service__pb2.GetSeasonalStatsRequest.FromString,
                    response_serializer=protos_dot_service__pb2.GetSeasonalResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'PredictionAnalytics.PredictionAnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('PredictionAnalytics.PredictionAnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class PredictionAnalyticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def UploadCSV(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PredictionAnalytics.PredictionAnalyticsService/UploadCSV',
            protos_dot_service__pb2.UploadCSVRequest.SerializeToString,
            protos_dot_service__pb2.UploadCSVResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSeasonalStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/PredictionAnalytics.PredictionAnalyticsService/GetSeasonalStats',
            protos_dot_service__pb2.GetSeasonalStatsRequest.SerializeToString,
            protos_dot_service__pb2.GetSeasonalResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
