# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14protos/service.proto\x12\x13PredictionAnalytics\"(\n\x10UploadCSVRequest\x12\x14\n\x0c\x66ile_content\x18\x01 \x01(\x0c\"4\n\x11UploadCSVResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"0\n\x17GetSeasonalStatsRequest\x12\x15\n\rfacility_name\x18\x01 \x01(\t\"Y\n\tDataPoint\x12\x0e\n\x06season\x18\x01 \x01(\t\x12\x0e\n\x06\x63olumn\x18\x02 \x01(\t\x12\x0e\n\x06median\x18\x03 \x01(\x01\x12\r\n\x05lower\x18\x04 \x01(\x01\x12\r\n\x05upper\x18\x05 \x01(\x01\";\n\tChartData\x12.\n\x06points\x18\x01 \x03(\x0b\x32\x1e.PredictionAnalytics.DataPoint\"I\n\x13GetSeasonalResponse\x12\x32\n\nchart_data\x18\x01 \x01(\x0b\x32\x1e.PredictionAnalytics.ChartData2\xe4\x01\n\x1aPredictionAnalyticsService\x12Z\n\tUploadCSV\x12%.PredictionAnalytics.UploadCSVRequest\x1a&.PredictionAnalytics.UploadCSVResponse\x12j\n\x10GetSeasonalStats\x12,.PredictionAnalytics.GetSeasonalStatsRequest\x1a(.PredictionAnalytics.GetSeasonalResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_UPLOADCSVREQUEST']._serialized_start=45
  _globals['_UPLOADCSVREQUEST']._serialized_end=85
  _globals['_UPLOADCSVRESPONSE']._serialized_start=87
  _globals['_UPLOADCSVRESPONSE']._serialized_end=139
  _globals['_GETSEASONALSTATSREQUEST']._serialized_start=141
  _globals['_GETSEASONALSTATSREQUEST']._serialized_end=189
  _globals['_DATAPOINT']._serialized_start=191
  _globals['_DATAPOINT']._serialized_end=280
  _globals['_CHARTDATA']._serialized_start=282
  _globals['_CHARTDATA']._serialized_end=341
  _globals['_GETSEASONALRESPONSE']._serialized_start=343
  _globals['_GETSEASONALRESPONSE']._serialized_end=416
  _globals['_PREDICTIONANALYTICSSERVICE']._serialized_start=419
  _globals['_PREDICTIONANALYTICSSERVICE']._serialized_end=647
# @@protoc_insertion_point(module_scope)
